"""
Single-source-of-truth for the 52-email drip sequence metadata.
"""
from typing import List

_SEQ_DAY_OFFSETS: List[int] = [
    0, 3, 7, 10, 14, 17, 21, 24, 28, 31, 35, 38,
    42, 45, 49, 52, 56, 59, 63, 66, 70, 73, 77, 80,
    84, 87, 91, 94, 98, 101, 105, 108, 112, 115, 119, 122,
    126, 129, 133, 136, 140, 143, 147, 150, 154, 157, 161, 164,
    168, 171, 175, 178,
]

_SEQ_SUBJECTS: List[str] = [
    "You're not lazy — you just don't have the right system yet",
    "The top student in your class isn't smarter than you",
    "Your grades reflect your habits — not your potential",
    "Two students. Same exam. The only difference is what they believe about it.",
    "Every great performer you admire was once a beginner who found the right method",
    "The curiosity you had as a child didn't disappear — it was buried",
    "Your brain doesn't record like a camera — it builds like a scaffold",
    "Barbara Oakley couldn't do maths. Then she learned how the brain actually changes.",
    "You've been studying the wrong way (and it feels productive)",
    "If studying feels comfortable, something is probably wrong.",
    "Your brain processes visuals 60,000x faster than text. You're studying the slow way.",
    "You're not bad at remembering. You're bad at reviewing. Different problem.",
    "The most powerful study technique has been proven for 100+ years. You're not using it.",
    "One technique mastered beats ten techniques practised",
    "Your notes aren't the problem — what you do after is",
    "The real reason you can't focus when you study",
    "This student studied 4 hours a day and outscored the 12-hour grinders",
    "There's a point where more studying actively destroys your performance.",
    "You're not multitasking — you're just switching fast and paying the cost",
    "Your mind wanders 47% of the time. Here's what to do about it.",
    "Every unfinished task in your head is quietly draining your focus",
    "Flow is not luck. It has trigger conditions — and you can set them.",
    "You have the same 24 hours as every top student. Here's what they do differently.",
    "The world's smartest people use checklists. Here's why you should too.",
    "Motivation is the spark. You can't run an engine on sparks.",
    "You don't need more discipline — you need a smaller starting point",
    "It's not a discipline problem. It's a design problem.",
    "The gap between average and excellent isn't talent — it's one habit",
    "One habit. Twenty minutes. Every week. The results are remarkable.",
    'Every Monday is "the new start." At what point does the pattern become the problem?',
    "You already know what you should be doing. That's not the problem.",
    "Your grades are built in the moments nobody sees",
    "Working hard on the wrong things is worse than not working at all",
    "Stop blaming yourself for your grades. Fix the system upstream.",
    "The best student in the room isn't the hardest worker — they're the most strategic",
    "MIT in 12 months — and what it reveals about how you're wasting yours",
    "The most powerful career question applies to your academic life right now",
    '"Balance" is not about doing everything equally. Here\'s what it actually means.',
    "Exam anxiety has nothing to do with the exam",
    "The most pressure-proof students aren't fearless — they're prepared differently",
    "There's a kind of suffering nobody talks about — slow, invisible progress",
    "You won't notice it happening. Then one day you'll be unrecognisable.",
    "The most powerful motivation isn't external. It's a clear picture of who you're becoming.",
    "What you do in the next 90 days will still matter in 2031.",
    "A mentor doesn't do the work for you — they show you which work matters",
    "Michael Jordan had a coach. What makes you think you should do this alone?",
    "He was three failed courses in and considering dropping out. Six months later:",
    "The decision to not decide is itself a decision. And it has a price.",
    "I'm not going to sell you. I'm going to tell you the truth about why this exists.",
    "Let me show you what the before and after actually looks like.",
    "The argument against investing in yourself is made by the version of you that benefits least.",
    "One question left.",
]
